#!/usr/bin/python3
#+
# This script converts the system-installed Unicode tables into a form
# suitable for use by the Android app.
#
# Copyright 2013 Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
import re

src_file = "/usr/share/unicode/NamesList.txt"
versionstr = "@@@\tThe Unicode Standard "

with open(file = src_file, errors = "ignore") as src :
    charcode = None
    char_category = None
    eof = False
    line = src.readline().rstrip()
    if line.startswith(versionstr) :
        version = line[len(versionstr):]
        sys.stdout.write("Unicode version: “%s”\n" % version)
    else :
        raise AssertionError("first line doesn’t contain version")
    #end if
    while True :
        line = src.readline()
        if len(line) == 0 :
            eof = True
        #end if
        nextcharcode = None
        if not eof :
            line = line.rstrip()
            if len(line) != 0 :
                nextcharcode = re.match(r"[0-9A-F]+", line)
                if nextcharcode != None :
                    line = line[nextcharcode.end():]
                #end if
            #end if
        #end if
        if (eof or nextcharcode != None) and charcode != None :
            sys.stdout.write \
              (
                    "* U+%04X “%s” (%s) = (%s), like (%s)\n"
                %
                    (
                        charcode,
                        charname,
                        char_category,
                        "; ".join(samechar),
                        "; ".join("U+%04X" % c for c in likechar),
                    )
              )
            charcode = None
        #end if
        if eof :
            break
        if nextcharcode != None :
            charcode = int(nextcharcode.group(), 16)
            assert line.startswith("\t")
            charname = line[1:]
            samechar = set()
            likechar = set()
        elif charcode != None and line.startswith("\t") :
            line = line[1:]
            if line.startswith("= ") :
                samechar.add(line[2:])
            elif line.startswith("x ") :
                nextpos = 2
                while True :
                    nextlikecharcode = re.search(r"[0-9A-F]+", line[nextpos:])
                    if nextlikecharcode == None :
                        break
                    likecharcode = int(nextlikecharcode.group(), 16)
                    nextpos += nextlikecharcode.end()
                #end while
                likechar.add(likecharcode)
            else :
                pass # sys.stdout.write("Ignore line for U+%04X: %s\n" % (charcode, repr(line)))
            #end if
        elif line.startswith("@\t\t") :
            char_category = line[3:]
        else :
            pass # sys.stdout.write("Ignore line: %s\n" % repr(line))
        #end if
    #end while
#end with
